import { InventoryItem, Upload } from "../types";
import { calculateResalePrice } from "./pricingService";

const userId = "user-123";

export const MOCK_UPLOADS: Upload[] = [
  {
    id: "up-1",
    user_id: userId,
    filename: "Winter_Collection_Batch_A.csv",
    status: "completed",
    total_rows: 82,
    success_count: 82,
    error_count: 0,
    created_at: "2023-10-24T14:30:00Z",
  },
  {
    id: "up-2",
    user_id: userId,
    filename: "Summer_Footwear_Clearance.csv",
    status: "processing",
    total_rows: 44,
    success_count: 22,
    error_count: 0,
    created_at: "2023-10-23T09:15:00Z",
  },
  {
    id: "up-3",
    user_id: userId,
    filename: "Accessories_Resale_List_Final.csv",
    status: "completed",
    total_rows: 30,
    success_count: 28,
    error_count: 2,
    created_at: "2023-10-21T11:45:00Z",
  },
];

const createItem = (
  id: string,
  title: string,
  brand: string,
  category: string,
  condition: "new" | "like_new" | "good" | "fair",
  origPrice: number,
  status: "pending" | "priced" | "listed" | "unlisted" | "sold",
  sku: string,
): InventoryItem => ({
  id,
  user_id: userId,
  merchant_id: "MERCH-001",
  sku,
  title,
  brand,
  category,
  condition,
  original_price: origPrice,
  currency: "ZAR",
  quantity: Math.floor(Math.random() * 5) + 1,
  resale_price: calculateResalePrice(origPrice, condition, category),
  is_price_manual: false,
  status,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
});

export const MOCK_INVENTORY: InventoryItem[] = [
  createItem(
    "1",
    "Slim Fit Chinos",
    "Levi Strauss & Co.",
    "Bottoms",
    "new",
    1200,
    "listed",
    "REU-9921",
  ),
  createItem(
    "2",
    "Oversized Knit Sweater",
    "Zara Eco-line",
    "Outerwear",
    "like_new",
    890,
    "priced",
    "REU-8842",
  ),
  createItem(
    "3",
    "Vintage Graphic Tee",
    "Nike",
    "Tops",
    "fair",
    450,
    "pending",
    "REU-7731",
  ),
  createItem(
    "4",
    "High-Waisted Denim",
    "H&M Conscious",
    "Bottoms",
    "new",
    799,
    "listed",
    "REU-1022",
  ),
  createItem(
    "5",
    "Silk Scarf",
    "Local Artisan",
    "Accessories",
    "good",
    320,
    "priced",
    "REU-6625",
  ),
  createItem(
    "6",
    "Classic Trench Coat",
    "Burberry",
    "Outerwear",
    "like_new",
    4500,
    "listed",
    "REU-5432",
  ),
  createItem(
    "7",
    "Floral Summer Dress",
    "Mango",
    "Dresses",
    "new",
    850,
    "priced",
    "REU-4321",
  ),
  createItem(
    "8",
    "Runner Pro Sneaker",
    "Adidas",
    "Shoes",
    "good",
    1400,
    "pending",
    "REU-3210",
  ),
  createItem(
    "9",
    "Leather Moto Jacket",
    "AllSaints",
    "Jackets",
    "like_new",
    3500,
    "priced",
    "REU-2109",
  ),
  createItem(
    "10",
    "Yoga Leggings",
    "Lululemon",
    "Activewear",
    "new",
    1100,
    "listed",
    "REU-1098",
  ),
];
